class Constants:
    INBOUND_SHORT_MESSAGE = "inboundShortMessage"
    NAME = "name"
    REFID = "refId"
    STATES = "states"
    STATE = "state"
    TASKS = "tasks"
    TASK = "task"
    ACTIONS = "actions"
    CALL_TASK = "callTask"
    UPDATEDATA_TASK = "updateData"
    SETPARTICIPANTDATA_TASK = "setParticipantData"
    END_TASK = "endTask"
    SWITCH_TASK = "switch"
    DECISION_TASK = "decision"
    TRANSFERTOACD_TASK = "transferToAcd"
